apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-login-service
  labels:
    app: user-manager
spec:
  type: {{ .Values.service.type }}
  selector:
    app: user-manager
  ports:
  - name: endpoint
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
