apiVersion: v1
kind: Service
metadata:
  name: frontendload
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "frontend-loadbalancer"
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

