apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-table
spec:
#  replicas: 2
  selector:
    matchLabels:
      app: parking-table
  template:
    metadata:
      labels:
        app: parking-table
    spec:
      containers:
      - name: parking-table
        image: fabhiahn/parkster-table:v1.3
        ports:
        - containerPort: 5001
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 120
        env:
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: JWT_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: parking-service
spec:
  type: ClusterIP
  selector:
    app: parking-table
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
