name: Build and Push Docker Images

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'microservices/user-management-service/**'
      - 'microservices/parking-service/**'
      - 'frontend/**'
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PAT }}

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push user-management-service image
        working-directory: microservices/user-management-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/parkster-login:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/parkster-login:latest ${{ secrets.DOCKER_USERNAME }}/parkster-login:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/parkster-login:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/parkster-login:${{ github.sha }}

      - name: Build and push parking-service image
        working-directory: microservices/parking-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/parkster-table:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/parkster-table:latest ${{ secrets.DOCKER_USERNAME }}/parkster-table:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/parkster-table:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/parkster-table:${{ github.sha }}

      - name: Build and push frontend image
        working-directory: frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/parkster-frontend:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/parkster-frontend:latest ${{ secrets.DOCKER_USERNAME }}/parkster-frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/parkster-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/parkster-frontend:${{ github.sha }}
