name: User Management pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'microservices/user-management-service/**'
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PAT }}

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push user-management-service image
        working-directory: microservices/user-management-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/parkster-login:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/parkster-login:latest ${{ secrets.DOCKER_USERNAME }}/parkster-login:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/parkster-login:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/parkster-login:${{ github.sha }}

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig=~/.kube/config set image deployment/user-manager user-manager=${{ secrets.DOCKER_USERNAME }}/parkster-login:${{ github.sha }}
          kubectl --kubeconfig=~/.kube/config rollout status deployment/user-management-deployment

      
